### ISSUE TITLE
Distorted fonts in Termux with Blue-Minimal

### ISSUE THREAD

**Issue by sebastian-de** [scoute-dich/Blue-Minimal#28] opened 2017-04-11 16:07 UTC
Hi, I really like Blue-Minimal and I use it on I Nexus 5 with CM13, thanks for releasing it!
I noticed just one small issue:
When applying the fonts of the theme, the characters in Termux look distorted, especially thin characters like "l" or "i". When using the CM default theme, the terminal font looks fine.

Screenshot:
![screenshot_20170411-072451](https://cloud.githubusercontent.com/assets/7430495/24918286/2ea49618-1ee0-11e7-983f-2a9ce25cd49b.png)

For now, I'm just using a different font in Termux, but it would be nice if Blue-Minimal and Termux looked nice together out of the box.

Greetings
Sebastian

**Comment by scoute-dich** [comment] 2017-04-15 18:32
I will lokk at it. Thanks for reporting.

**Comment by scoute-dich** [comment] 2017-04-17 20:06
Since I'm on Android Nougat and LineAgeOS doesn't have the theme engine implemented, I'm working on a Substratum theme. There I implemented Fira font. You can find it on Google webfonts. If it would be ok for you I could use the same font for the CM theme. The advantage would be that for fira font there are more font styles. I think in the currently used font (Roboto) there are some missing styles.

I have two font packs a thinner one and a normal. At the moment I'm not at home and can't attach screenshots.

So what do you think?

Regards
Gaukler Faun

**Comment by sebastian-de** [comment] 2017-04-20 16:02
Fira fonts looks fine in Termux, I think it's a good choice.
I don't know which variant they package, looks like the normal one, so I'd go with that. (the Termux font file is here: https://github.com/termux/termux-styling/blob/master/app/src/main/assets/fonts/FiraCode.ttf )

I wanted to wait for a LineageOS release before switching, but maybe I'll install the nightlies if they seem stable enough. Do the nightlies contain the Substratum engine already?

Thank you for your work and support, I'll send a donation the coming days.

Regards
Sebastian

**Comment by scoute-dich** [comment] 2017-04-21 14:52
Ok. Then I will change this (this weekend).

**Comment by scoute-dich** [comment] 2017-04-21 19:36
I've made an apk file (just rename  zip to apk). Perhaps you can test it and report, if the issue is gone.

LineAgeOS supports Substratum not in all points:

- it needs root
- you must reboot to apply overlays
- no fonts, bootanimation and wallpaper support
- audio support works not on my phone

But it's ok. Wallpaper and audio you can choose with opther apps or the system settings. Bootanimation and fonts you can flash via recovery. I#m working on a substratum theme based on my "CM theme".

All in all LOS works fine on my four year old not1. No major bugs.

Regards
Gaukler Faun

[theme-debug.zip](https://github.com/scoute-dich/Blue-Minimal/files/948129/theme-debug.zip)

**Comment by sebastian-de** [comment] 2017-04-22 09:36
![screenshot_20170422-112342](https://cloud.githubusercontent.com/assets/7430495/25303236/f0e959ea-274e-11e7-913f-4cceccb1c788.png)
Doesn't seem to work, the font changed, but with the same problem.
It looks like Termux doesn't pick the monospace font, it just stetches the sans font. Hard to tell from my side, if this is a Termux or a theme issue. Do you know any other freely available CM13 Theme with altered fonts? I could try one and see if the issue is present there.

**Comment by scoute-dich** [comment] 2017-04-24 16:42
I don't know a other theme. At the moment I#m using substratum and before I used (of course) my theme.

Next approach. I added a monospace font. Perhaps you can test it again. (Rename .zip to .apk) Thanks for your patience.
[theme-debug.zip](https://github.com/scoute-dich/Blue-Minimal/files/952441/theme-debug.zip)

**Comment by sebastian-de** [comment] 2017-04-24 19:04
This one worked, Termux now uses the monospace font. Thank you very much for your support!
Do you plan to release this fix as an updated version of the CM13 Theme on f-droid, or will the next release be substratum only?
Should I close this issue right away, or wait for the release?

Am 24. April 2017 18:42:47 MESZ schrieb Gaukler Faun <notifications@github.com>:
>I don't know a other theme. At the moment I#m using substratum and
>before I used (of course) my theme.
>
>Next approach. I added a monospace font. Perhaps you can test it again.
>(Rename .zip to .apk) Thanks for your patience.
>[theme-debug.zip](https://github.com/scoute-dich/Blue-Minimal/files/952441/theme-debug.zip)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/scoute-dich/Blue-Minimal/issues/28#issuecomment-296736592

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by scoute-dich** [comment] 2017-04-24 19:24
Of course I will release this fix. And I plan also to maintain the project in future if there are bugs.

I think we can close the issue.

Regards
Gaukler Faun

**Closed** 2017-04-24 19:24 UTC
