### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by conrad-heimbold** [scoute-dich/Blue-Minimal#29] opened 2017-05-06 20:37 UTC
version: 4.9 from F-Droid

Is it my fault, that I don't have Roboto-Condensed.ttf on my phone, or should it be included in your app? 

```
--------- beginning of crash
05-06 22:31:25.707 27339 27339 E AndroidRuntime: FATAL EXCEPTION: main
05-06 22:31:25.707 27339 27339 E AndroidRuntime: Process: de.baumann.thema, PID: 27339
05-06 22:31:25.707 27339 27339 E AndroidRuntime: Theme: themes:{default=overlay:org.cyanogenmod.hexolibre, iconPack:ovh.ice.icecons, fontPkg:system, com.android.systemui=overlay:org.cyanogenmod.hexolibre, com.android.systemui.navbar=overlay:system}
05-06 22:31:25.707 27339 27339 E AndroidRuntime: java.lang.RuntimeException: Font asset not found fonts/Roboto-Condensed.ttf
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.graphics.Typeface.createFromAsset(Typeface.java:198)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at de.baumann.thema.FragmentRequest$AppAdapter.getView(FragmentRequest.java:513)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2346)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.ListView.makeAndAddView(ListView.java:1876)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.ListView.fillDown(ListView.java:702)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.ListView.fillFromTop(ListView.java:763)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.ListView.layoutChildren(ListView.java:1685)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.AbsListView.onLayout(AbsListView.java:2148)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.View.layout(View.java:16639)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.View.layout(View.java:16639)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.View.layout(View.java:16639)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.View.layout(View.java:16639)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.View.layout(View.java:16639)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.View.layout(View.java:16639)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1391)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.View.layout(View.java:16639)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.View.layout(View.java:16639)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.View.layout(View.java:16639)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.View.layout(View.java:16639)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.View.layout(View.java:16639)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2934)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at android.view.View.layout(View.java:16639)
05-06 22:31:25.707 27339 27339 E AndroidRuntime: 	at androi
05-06 22:31:25.710   969  1854 W ActivityManager:   Force finishing activity de.baumann.thema/.Screen_Main
05-06 22:31:25.773   969 27400 W DropBoxManagerService: Dropping: data_app_crash (10 > 0 bytes)
05-06 22:31:25.785   969  6085 I OpenGLRenderer: Initialized EGL, version 1.4
05-06 22:31:25.968   969   979 I art     : Background partial concurrent mark sweep GC freed 30297(1392KB) AllocSpace objects, 0(0B) LOS objects, 33% free, 28MB/42MB, paused 3.937ms total 239.586ms
05-06 22:31:26.237   969   983 W ActivityManager: Activity pause timeout for ActivityRecord{ecfb268 u0 de.baumann.thema/.Screen_Main t272 f}
05-06 22:31:26.251 17023 17023 W Launcher: setApplicationContext called twice! old=com.android.launcher3.LauncherApplication@30cf7c2 new=com.android.launcher3.LauncherApplication@30cf7c2
05-06 22:31:26.404 17023 19487 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
05-06 22:31:26.404 17023 19487 I OpenGLRenderer: Initialized EGL, version 1.4
05-06 22:31:26.579   969   989 I ActivityManager: Displayed com.cyanogenmod.trebuchet/com.android.launcher3.Launcher: +340ms
05-06 22:31:27.273 27339 27339 I Process : Sending signal. PID: 27339 SIG: 9
05-06 22:31:27.343   969  1864 D GraphicsStats: Buffer count: 6
05-06 22:31:27.343   969 22599 I WindowState: WIN DEATH: Window{8cc4f0a u0 de.baumann.thema/de.baumann.thema.Screen_Main}
05-06 22:31:27.381   969  8405 I ActivityManager: Process de.baumann.thema (pid 27339) has died
05-06 22:31:27.382   969  8405 D ActivityManager: cleanUpApplicationRecord -- 27339
05-06 22:31:27.550   969   989 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
```

**Comment by CFPrulez** [comment] 2017-05-11 16:58
I can confirm this crash, running the latest version (4.9) on Android 7.1.2/LineageOS 14.1. 

Will 14.1 be supported or is the app intended to work only on CM12/CM13?

**Comment by scoute-dich** [comment] 2017-05-11 17:40
I will look in that today.

CM 14 (jet LineAgeOS) won't be supported, since there is no theme engine implemented. But I created a substratum theme with the same functionality (overlay, boot animation, sounds, icons, fonts). The repo is called "Minimal". If you want I can publish there a release... Just tell me. But at the moment there are not many icons implemented.

You can also use __this__  theme with a custom launcher with icon pack support.

**Comment by scoute-dich** [comment] 2017-05-11 18:18
Fixed. Update may take some time. At the moment F-Droid needs up to seven days to publish an update.  :-(

**Closed** 2017-07-15 10:12 UTC
